stages:
  - test
  - deploy


test:
  stage: test
  image: python
  script:
    - apt-get -q update
    - ./latest-firefox.sh
    - apt-get -yq install Xvfb
    - pip install -r requirements.txt
    - initial_dir=`pwd`
    - cd /usr/bin
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
    - tar -xvzf geckodriver*
    - chmod +x geckodriver
    - cd $initial_dir
    - export DISPLAY=:1
    - python manage.py test
