stages:
  - test
  - deploy


test:
  stage: test
  image: python
  script:
    - apt-get -q update
    - apt-get -yq install firefox-esr
    - wget -O FirefoxSetup.tar.bz2 "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US"
    - mkdir /opt/firefox
    - tar xjf FirefoxSetup.tar.bz2 -C /opt/firefox/
    - mv /usr/lib/firefox-esr/firefox-esr /usr/lib/firefox-esr/firefox-esr_orig
    - ln -s /opt/firefox/firefox/firefox /usr/lib/firefox-esr/firefox-esr
    - apt-get -yq install Xvfb
    - pip install -r requirements.txt
    - initial_dir=`pwd`
    - cd /usr/bin
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
    - tar -xvzf geckodriver*
    - chmod +x geckodriver
    - cd $initial_dir
    - export DISPLAY=:1
    - python manage.py test
