# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-21 18:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_default_currencies(apps, schema_editor):
    Currency = apps.get_model('financial', 'Currency')
    Currency.objects.create(name='IRR')
    Currency.objects.create(name='EUR')
    Currency.objects.create(name='USD')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_amount', models.DecimalField(decimal_places=64, max_digits=128)),
                ('to_amount', models.DecimalField(decimal_places=64, max_digits=128)),
                ('status', models.CharField(choices=[('created', 'Created'), ('failed', 'Failed'), ('succeeded', 'Succeeded')], default='created', max_length=32)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='going_transaction_set', to='financial.Currency')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='going_transaction_set', to=settings.AUTH_USER_MODEL)),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coming_transaction_set', to='financial.Currency')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coming_transaction_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(add_default_currencies)
    ]
