# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 13:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='from_user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='going_transaction_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='coming_transaction_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
