# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-25 06:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=64, max_digits=128)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.Currency')),
                ('dst_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coming_anonymousRequest_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=64, max_digits=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In progress'), ('failed', 'Failed'), ('succeeded', 'Succeeded'), ('suspicious', 'Suspicious')], default='created', max_length=32)),
                ('attachment', models.FileField(upload_to='')),
                ('user_description', models.TextField()),
                ('employee_description', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeComing_request_set', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.Transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userGoing_request_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestTypeBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('wage_rule', models.CharField(default='0 0', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRequestType',
            fields=[
                ('requesttypebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflow.RequestTypeBase')),
                ('dst_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coming_exchangeRequestType_set', to='financial.Currency')),
                ('src_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='going_exchangeRequestType_set', to='financial.Currency')),
            ],
            bases=('workflow.requesttypebase',),
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('requesttypebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflow.RequestTypeBase')),
                ('amount', models.DecimalField(blank=True, decimal_places=64, max_digits=128, null=True)),
                ('information', models.TextField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.Currency')),
            ],
            bases=('workflow.requesttypebase',),
        ),
        migrations.AddField(
            model_name='anonymousrequest',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.RequestTypeBase'),
        ),
        migrations.AddField(
            model_name='anonymousrequest',
            name='src_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='going_anonymousRequest_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anonymousrequest',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.Transaction'),
        ),
        migrations.AddField(
            model_name='request',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.RequestType'),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.ExchangeRequestType'),
        ),
    ]
