# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20180615_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesttype',
            name='id',
        ),
        migrations.AddField(
            model_name='requesttype',
            name='requesttypebase_ptr',
            field=models.OneToOneField(auto_created=True, default=-1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflow.RequestTypeBase'),
            preserve_default=False,
        ),
    ]
