# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-21 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20180616_1315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExchangeRequest',
            new_name='ExchangeRequestType',
        ),
    ]
